name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-demo:latest .

      # 4. Run simple tests
      - name: Run Tests
        run: |
          echo "Tests passed"
