name: Docker CI

# Trigger the workflow on push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t flask-docker-demo .

      # Step 4: Run simple tests
      - name: Run tests
        run: echo "Tests passed"

      # Step 5: Simulate pushing to DockerHub
      - name: Push Docker image (simulated)
        run: echo "Skipping actual push to DockerHub"

